main_app/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('vacas/', views.vacas_index, name='vacas_index'),
    path('vacas/<int:vaca_id>/', views.vacas_detail, name='vacas_detail'),
    path('vacas/create/', views.VacasCreate.as_view(), name='vacas_create'),
    path('vacas/<int:pk>/update/', views.VacasUpdate.as_view(), name='vacas_update'),
    path('vacas/<int:pk>/delete/', views.VacasDelete.as_view(), name='vacas_delete'),
    path('vacas/<int:vaca_id>/add_traveling/', views.add_traveling, name='add_traveling'),
    path('stuff/create/', views.StuffsCreate.as_view(), name='stuffs_create'),
    path('stuffs/', views.StuffsIndex.as_view(), name='stuffs_index'),
    path('stuffs/<int:pk>/', views.StuffsDetail.as_view(), name='stuffs_detail'),
    path('stuffs/<int:pk>/update/', views.StuffsUpdate.as_view(), name='stuffs_update'),
    path('stuffs/<int:pk>/delete/', views.StuffsDelete.as_view(), name='stuffs_delete'),
    path('vacas/<int:vaca_id>/assoc_stuff/<int:stuff_id>/', views.assoc_stuff, name='assoc_stuff'),
    path('vacas/<int:vaca_id>/add_photo', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

thegetaway/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from random import choices
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Stuff(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return f'A {self.description} {self.name}'
    
    def get_absolute_url(self):
        return reverse('stuffs_detail', kwargs={'pk': self.id})

class Vaca(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    cost = models.CharField(max_length=100)
    stuffs = models.ManyToManyField(Stuff)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('vacas_detail', kwargs={'vaca_id': self.id})

class Traveling(models.Model):
    MOODS = (
        ('B', 'Bad'),
        ('O', 'OK'),
        ('G', 'Good'),
        ('L', 'Loved it'),
    )

    class Meta:
        ordering = ('-date',)

    date = models.DateField('traveling date')
    mood = models.CharField(max_length=1, choices=MOODS, default=MOODS[0][0])
    vaca = models.ForeignKey(Vaca, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_mood_display()} on {self.date}'

class Photo(models.Model):
    url = models.CharField(max_length=200)
    vaca = models.ForeignKey(Vaca, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for vaca_id: {self.vaca_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm 
from .models import Traveling

class TravelingForm(ModelForm):
    class Meta:
        model = Traveling 
        fields = ('date', 'mood')

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect

from .models import Vaca, Stuff, Photo

from django.contrib.auth import login

from .forms import TravelingForm

from django.contrib.auth.forms import UserCreationForm

import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'cat-collector-photo-upload-29'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def vacas_index(request): 
    vacas = Vaca.objects.all()
    return render(request, 'vacas/index.html', {'vacas' : vacas})

@login_required
def vacas_detail(request, vaca_id):
    vaca = Vaca.objects.get(id=vaca_id)
    traveling_form = TravelingForm()
    stuffs = Stuff.objects.exclude(id__in=vaca.stuffs.all().values_list('id'))
    return render(request, 'vacas/detail.html', {
        'vaca': vaca,
        'traveling_form' : traveling_form,
        'stuffs' : stuffs
        })

@login_required
def add_traveling(request, vaca_id):
    print(request.POST)
    form= TravelingForm(request.POST)
    if form.is_valid():
        new_traveling = form.save(commit=False)
        new_traveling.vaca_id = vaca_id
        new_traveling.save()
    else:
        print(form.errors)
    return redirect('vacas_detail', vaca_id=vaca_id)

@login_required
def assoc_stuff(request, vaca_id, stuff_id):
    Vaca.objects.get(id=vaca_id).stuffs.add(stuff_id)
    return redirect('vacas_detail', vaca_id=vaca_id)


@login_required
def add_photo(request, vaca_id):
    photo_file = request.FILES.get('photo-files')
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f'{S3_BASE_URL}{BUCKET}/{key}'
            photo = Photo(url=url, vaca_id=vaca_id)
            photo.save()
        except Exception as error:
            print('An error has occured uploading or saving the new photo')
            print(error)
    return redirect('vacas_detail', vaca_id=vaca_id)


def signup(request):
    error_message = None
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('vacas_index')
        else:
            error_message = 'Signup input invalid - Please try again'
    form = UserCreationForm()
    context = { 'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context)

class VacasCreate(LoginRequiredMixin, CreateView):
    model = Vaca
    fields = ('name', 'location', 'city', 'description', 'cost')

class VacasUpdate (LoginRequiredMixin, UpdateView):
    model = Vaca
    fields = ('description', 'cost')

class VacasDelete(LoginRequiredMixin, DeleteView):
    model = Vaca
    success_url = '/vacas/'

class StuffsCreate(LoginRequiredMixin, CreateView):
    model = Stuff
    fields = ('name', 'description')

class StuffsIndex(LoginRequiredMixin, ListView):
    template_name = 'stuffs/index.html'
    model = Stuff

class StuffsDetail(LoginRequiredMixin, DetailView):
    template_name = 'stuffs/detail.html'
    model = Stuff

class StuffsUpdate(LoginRequiredMixin, UpdateView):
    model = Stuff
    fields = ('name', 'description')

class StuffsDelete(LoginRequiredMixin, DeleteView):
    model = Stuff
    success_url = '/stuffs/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
About | The GetaWay
{% endblock %}

{% block content %}
    <p> This is the place to really GetaWay. See youre past vacations and even ones up to come. Post things that make you happy or emoitional. Make a memory and love your life. </p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo">The GetaWay</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'vacas_index' %}">View the My Vacations</a></li>
            <li><a href="{% url 'vacas_create' %}">Add New Memory</a></li>
            <li><a href="{% url 'stuffs_index' %}">Things to do</a></li>
            <li><a href="{% url 'stuffs_create' %}">Add New Thing to do</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href= "{% url 'signup' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
        {% block content %} 
        {% endblock %}
    </main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, © 2022 The GetaWay 
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home | The GetaWay
{% endblock %}
{% block style%}
{% endblock %}
{% block content %}

{% endblock %}

main_app/templates/main_app/stuff_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure You Want to Delete Your {{object.color}} {{ object.name }}? | Cat Collector

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete your {{ object.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'stuffs_detail' object.id %}">No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/stuff_form.html
{% extends 'base.html' %}

{% block title %}

Add New ToDp | The GetaWay

{% endblock %}

{% block content %}

{% if object %}
<h1>Edit <span>{{ object.name }} </span>{{object.description}}</h1>
{% else %}
<h1> Add New ToDo</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %} Update {% else %} Add New {% endif %}" class="btn green" />
</form>

{% endblock %}

main_app/templates/main_app/vaca_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure You Want to Delete {{ object.name }}? | The GetaWay

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'vacas_detail' object.id %}">No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/vaca_form.html
{% extends 'base.html' %}

{% block title %}

Add a New Toy | Dog Collector

{% endblock %}

{% block content %}

{% if object %}
<h1>Edit <span>{{ object.name }} </span>{{object.description}}</h1>
{% else %}
<h1> Add New ToDp</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %} Update {% else %} Add New {% endif %}" class="btn green" />
</form>

{% endblock %}

main_app/templates/stuffs/detail.html
{% extends 'base.html' %}

{% block title %}

Details for {{ object.name }} | The GetaWay

{% endblock %}


{% block content %}

<h1>To Do List details Details</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">
            {{ stuff.name }}-<span class="{{ stuff.color }}-text">{{stuff.description.capitalize}}</span>
        </span>
    </div>
    <div class="card-action">
        <a href="{% url 'stuffs_update' object.id %}">Update</a>
        <a href="{% url 'stuffs_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/stuffs/index.html
{% extends 'base.html' %}

{% block title %}
Things to do Index | The GetaWay
{% endblock %}

{% block content %}
<h1>Index</h1>

{% for stuff in object_list %}
<a href="{% url 'stuffs_detail' stuff.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">
                {{ stuff.name }}-<span class="{{ stuff.color }}-text">{{stuff.description.capitalize}}</span>
            </span>
        </div>
    </div>
</a>
{% endfor %}


{% endblock %}

main_app/templates/vacas/detail.html
{% extends 'base.html' %}

{% block title %}

Details for {{ Vacations.name }} | GetaWay Collector

{% endblock %}


{% block content %}

<h1>Vacation Details</h1>
<div class="row">

    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ vaca.name }}</span>
                <p>Location: {{ vaca.location }}</p>
                <p>City: {{ vaca.city }}</p>
                <p>Description: {{ vaca.description }}</p>
                <p>Cost: {{ vaca.cost }}</p>
            </div>
            <div class="card-action"> 
                <a href="{% url 'vacas_update' vaca.id %}">Update</a>
                <a href="{% url 'vacas_delete' vaca.id %}">Delete</a>
            </div>
        </div>
        {% for photo in vaca.photo_set.all %}
            <img class="responsive-img card-panel"
             src="{{ photo.url }}"
             alt="{{ vaca.name }}"
             />
        {% empty %}
            <div class="card-panel blue-text center-align">
                No Photos Uploaded
            </div>
        {% endfor %}
        <form action="{% url 'add_photo' vaca.id %}" 
            method="POST"
            class="card-panel"
            enctype="multipart/form-data"
        >
            {% csrf_token %}
            <input type="file" name="photo-files"/>
            <br />
            <br />
            <input type="submit" value="Upload Photo" class="btn blue">
        </form>
    </div>
    <div class="col s6">

        <form action="{% url 'add_traveling' vaca.id %}" method="POST">
            {% csrf_token %}
            {{ traveling_form.as_p }}
            <input class="btn blue" type="submit" value="Add Date Traveled">
        </form>

        <table class="striped">
            <thread>
                <tr>
                    <th>Date</th>
                    <th>Rating</th>
                </tr>
            </thread>
            <tbody>
                {% for traveling in vaca.traveling_set.all %}
                <tr>
                    <td>{{ traveling.date }}</td>
                    <td>{{ traveling.get_mood_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
<div class="row">
    <div class="col s6">
        <h3>Compeleted</h3>
        {% if vaca.stuffs.count %}
            {% for stuff in vaca.stuffs.all %}
            <div class='card'>
                <div class="card-content">
                    <span class="card-title">
                        <span class="{{ stuff.color }}-text">{{stuff.description.capitalize}}</span> {{ stuff.name }}
                    </span>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <h5>{{vaca.name}}</h5>
        {% endif %}
    </div>
    <div class=" col s6">
        <h3> Todo List </h3>
        {% if stuffs.count %}
            {% for stuff in stuffs.all %}
            <div class='card'>
                <div class="card-content">
                    <span class="card-title">
                        <span>{{ stuff.name }}-{{stuff.description.capitalize}} 
                    </span>
                </div>
                
                <div class="card-action">
                    <form action="{% url 'assoc_stuff' vaca.id stuff.id %}" method="POST">
                        {% csrf_token %}
                        <input class="btn blue" type="submit" value="Add">
                    </form>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h5> A Trip WELL DONE</h5>
        {% endif %}
    </div>
</div>



<script> 
    const dateField = document.getElementById('id_date');
    const moodSelect = document.getElementById('id_mood');

    M.Datepicker.init(dateField, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    M.FormSelect.init(moodSelect);
</script>
    {% endblock %}

main_app/templates/vacas/index.html
{% extends 'base.html' %}

{% block title %}

Vacations Index | The GetaWay

{% endblock %}

{% block content %}

<h1> Vacations Index </h1>



{% for vaca in vacas %}
<a href="{% url 'vacas_detail' vaca.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ vaca.name }}</span>
            <p>Location: {{ vaca.location }}</p>
            <p>City: {{ vaca.city }}</p>
            <p>Description: {{ vaca.discription }}</p>
            <p>Cost: {{ vaca.cost }}</p>
           
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}